name: radlet_composer
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+4
  
  cupertino_icons: ^0.1.2
  
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  
  google_sign_in: ^4.1.4

  rxdart: ^0.23.1

  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true 
  ios: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
   - family: Roboto
     fonts:
      - asset: fonts/roboto.ttf 

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/
   - assets/images/
